### ISSUE TITLE
telloのカメラ情報が表示されない

### ISSUE THREAD

**Issue by yyyyymmmm12345** [GAI-313/Tello-Console#14]
サンプルコード(sample_video_2.py)を使用し、実行したところバッテリー残量などは表示されるが、カメラ映像は表示されませんでした。原因も不明なため、どのように対処すればよいか教えていただきたいです。
![image](https://user-images.githubusercontent.com/132982682/237013188-0536c2eb-3779-4f09-967f-51b6c2869d6e.png)
![image](https://user-images.githubusercontent.com/132982682/237013248-bec0996b-fab4-4e71-9907-5b78a9a73df9.png)

**Comment by GAI-313** [comment]
ご利用いただきあるがとうございます。現在まだ開発段階であり、不便をおかけして申し訳ございません。本問題は、以下の理由が挙げられます。

# 原因1
　Tello-Console Ver.7.1.0 以降からカメラストリームの仕様が変わり、**使用している Tello を最新のファームウェアにアップデートする必要があります。**<br>
　Tello-Console からも
```
ヒント：お使いの TELLO のファームウェアをアップデートしてください
...
```
と、ファームウェアが古いため一部機能が使用できないことを警鐘しています。このバージョンにより Tello からのビデオストリームプロトコルが変わっているため、既存の古いファームウェアでは受信不全を起こします。Tello-Console はこの不全を検出すると、自動的にストリーミングを停止します。

# 原因2
　使用しているドローンが TELLO EDU ではなく TELLO である。<br>
　Tello-Console は、**TELLO EDU** を使用することを前提としています。もし、**解決方法** を試しても成功しなかった場合、以下のメールに詳細を報告してください。件名に必ず **telloのカメラ情報が表示されない #14** を記述してください。

- nakartogawa.drone@gmail.com

# 原因3
　Windows との相性問題<br>
　お使いの環境が Windows と推測されます。Tello-Console は、README に書かれている通り、Windows との相性に問題を抱えています。現在調査、修正中ですが、以下の問題が発生することが確認されています。

- ビデオストリームに遅延が発生する
- コマンド送受信に遅延が生じる
- そもそも実行がブロックされる

もし、**解決方法** を試しても成功しなかった場合、以下のメールに詳細を報告してください。件名に必ず **telloのカメラ情報が表示されない #14** を記述してください。

- nakartogawa.drone@gmail.com

# 解決方法
　使用している Tello をアップデートしてください。アップデート方法は以下のサイトを参考にしてください。

- https://happydrone.info/column/telloupdaate8_19

# 解決できなかった場合
以下のメールに詳細を報告してください。件名に必ず **telloのカメラ情報が表示されない #14** を記述してください。

- nakartogawa.drone@gmail.com
